### ISSUE TITLE
version information

### ISSUE THREAD

**Issue by AnnaLaddach** [Fraternalilab/POPSlegacy#6]
It would be really useful to have the version information in the readme. I assume this is 1.8.1?

Thanks,

Anna

**Comment by jkleinj** [comment]
Hi Anna,

the version information is captured in the 'ChangeLog' file:
https://github.com/Fraternalilab/POPSlegacy/blob/master/ChangeLog

To check the version of a (compiled) release run 'pops --version',
otherwise run 'head configure.ac' and read the number in the AC_INIT line,
like 2.3.2 in this example:
AC_INIT(pops, 2.3.2, jens@jkleinj.eu).

  Jens
